# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 3.2.13 on 2022-04-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0008_auto_20220412_1515"),
    ]

    operations = [
        migrations.RemoveField(model_name="zaakobject", name="_etag",),
    ]
